USE ROLE {{ ROLE }}
USE DATABASE {{ DB }}

CREATE SCHEMA IF NOT EXISTS APP;
GRANT CREATE STAGE ON SCHEMA APP TO ROLE {{ ROLE }};

USE SCHEMA APP;

ALTER GIT REPOSITORY REPOSITORIES.CORTEX_LLM_DEMO FETCH;

CREATE OR REPLACE STREAMLIT APP.llm_demo
ROOT_LOCATION = '@REPOSITORIES.CORTEX_LLM_DEMO/branches/snowsight'
MAIN_FILE = '/app/app.py'
QUERY_WAREHOUSE = 'S';
