USE ROLE  &{ctx.env.SNOWFLAKE_ROLE};
USE DATABASE  &{ctx.env.SNOWFLAKE_DATABASE};
-- Schema to hold all file formats
CREATE SCHEMA IF NOT EXISTS FILE_FORMATS;
-- Database that will hold all stages
CREATE SCHEMA IF NOT EXISTS EXTERNAL_STAGES;
-- file format to load data from CSV
-- Default schema
USE SCHEMA PUBLIC;
CREATE FILE FORMAT IF NOT EXISTS FILE_FORMATS.CSVFORMAT
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TYPE = 'CSV';

-- s3 stage to load data files from
CREATE STAGE IF NOT EXISTS  EXTERNAL_STAGES.CALL_TRANSCRIPTS_DATA_STAGE
  FILE_FORMAT = FILE_FORMATS.CSVFORMAT
  URL = 's3://sfquickstarts/misc/call_transcripts/';

-- table that will be used in LLM queries
CREATE TABLE IF NOT EXISTS CALL_TRANSCRIPTS ( 
  DATE_CREATED DATE,
  LANGUAGE VARCHAR(60),
  COUNTRY VARCHAR(60),
  PRODUCT VARCHAR(60),
  CATEGORY VARCHAR(60),
  DAMAGE_TYPE VARCHAR(90),
  TRANSCRIPT VARCHAR
);

-- Load the data on the transcripts table
COPY INTO CALL_TRANSCRIPTS
  FROM @EXTERNAL_STAGES.CALL_TRANSCRIPTS_DATA_STAGE;