USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS &{ctx.env.SNOWFLAKE_ROLE};
GRANT ROLE &{ctx.env.SNOWFLAKE_ROLE} TO USER &{ctx.env.SNOWFLAKE_USER};
-- Database that will hold all demo data
CREATE DATABASE IF NOT EXISTS &{ctx.env.SNOWFLAKE_DATABASE};
GRANT OWNERSHIP ON DATABASE &{ctx.env.SNOWFLAKE_DATABASE} TO &{ctx.env.SNOWFLAKE_ROLE};
GRANT OWNERSHIP ON SCHEMA &{ctx.env.SNOWFLAKE_DATABASE}.PUBLIC TO &{ctx.env.SNOWFLAKE_ROLE};

-- GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE KAMESH_DEMOS_ROLE;

CREATE OR REPLACE API INTEGRATION kameshs_git_api_integration
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/kameshsampath')
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION kameshs_git_api_integration TO ROLE KAMESH_DEMOS_ROLE;


-- REVOKE CREATE INTEGRATION ON ACCOUNT FROM ROLE KAMESH_DEMOS_ROLE;