--!jinja
SET ROLE=KAMESH_DEMO_ROLE;
SET DB=KAMESH_LLM_DEMO;

USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS {{.ROLE}};
GRANT ROLE {{.ROLE}} TO USER CURRENT_USER;
-- Database that will hold all demo data
CREATE DATABASE IF NOT EXISTS {{.DB}};
GRANT OWNERSHIP ON DATABASE {{.DB}} TO {{.ROLE}};
GRANT OWNERSHIP ON SCHEMA {{.DB}}.PUBLIC TO {{.ROLE}};